import { Icon } from '@iconify/react';

export const metadata = {
    title: "Ambreena Shabbir",
    description: "Generated by create next app",
};

export default function Navbar() {
    return (
        <nav className="bg-white shadow-md">
            <div className="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
                <div className="flex items-center justify-between h-20">
                    <div className="flex-shrink-0">
                        <a className="text-2xl font-bold text-gray-800" href="#">
                            LOGO
                        </a>
                    </div>
                    <div className="hidden sm:flex sm:space-x-4">
                        <a href="#" className="text-gray-800 px-3 py-2 rounded-md text-sm font-medium">Home</a>
                        <a href="#" className="text-gray-800 px-3 py-2 rounded-md text-sm font-medium">About</a>
                        <a href="#" className="text-gray-800 px-3 py-2 rounded-md text-sm font-medium">Contact</a>
                    </div>
                    <div className="flex items-center gap-4">
                        <a href="#" className="text-gray-800">
                            <Icon icon="mdi:search" width="24" height="24" />
                        </a>
                        <a href="#" className="text-gray-800">
                            <Icon icon="mdi:user-outline" width="24" height="24" />
                        </a>
                        <a href="#" className="text-gray-800">
                            <Icon icon="mdi:cart-outline" width="24" height="24" />
                        </a>
                        <div className="sm:hidden">
                            <button className="inline-flex items-center justify-center p-2 rounded-md text-gray-800 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
                                <span className="sr-only">Open main menu</span>
                                <Icon icon="bi:list" width="24" height="24" />
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div className="sm:hidden">
                <div className="px-2 pt-2 pb-3 space-y-1">
                    <a href="#" className="text-gray-800 block px-3 py-2 rounded-md text-base font-medium">Home</a>
                    <a href="#" className="text-gray-800 block px-3 py-2 rounded-md text-base font-medium">About</a>
                    <a href="#" className="text-gray-800 block px-3 py-2 rounded-md text-base font-medium">Contact</a>
                </div>
            </div>
        </nav>
    );
}
